PizzaMamaDjango/pizzamama/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

PizzaMamaDjango/pizzamama/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

PizzaMamaDjango/pizzamama/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu-pizza/', include('menu.urls')),
    path('', include('main.urls')),
]

PizzaMamaDjango/pizzamama/main/models.py
from django.db import models

# Create your models here.

PizzaMamaDjango/pizzamama/menu/models.py
from django.db import models


class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

PizzaMamaDjango/pizzamama/main/views.py
from django.shortcuts import render
# from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, 'main/index.html')

PizzaMamaDjango/pizzamama/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza

# Create your views here.

# EXERCICE
# Les pizzas : Végétarienne : 8.5€, Poulet champignons : xxx, 4 fromages, Carnivore


def index(request):
    '''pizzas = Pizza.objects.all()
    pizzas_names_and_prices = [pizza.nom + " : " + str(pizza.prix) + "€" for pizza in pizzas]
    pizzas_names_and_prices_str = ", ".join(pizzas_names_and_prices)
    return HttpResponse("Les pizzas : " + pizzas_names_and_prices_str)'''
    pizzas = Pizza.objects.all().order_by('prix')
    return render(request, 'menu/index.html', {'pizzas': pizzas})

PizzaMamaDjango/pizzamama/main/templates/main/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pizza Mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centered">
        <img src="{% static 'main/images/main_logo.png' %}">
        <a href="{% url 'menu:index' %}">Voir le menu</a>
    </div>
</body>
</html>

PizzaMamaDjango/pizzamama/menu/templates/menu/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>

    <a href="{% url 'main:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}"></a>

    <div class="menu_title">
        <h1>Les pizzas</h1>
    </div>

    <div class="menu_list">
        {% for pizza in pizzas %}
        <div class="menu_list_item">
            <span class="menu_list_title">{{pizza.nom}}</span>
            <span class="menu_list_prix">{{pizza.prix | floatformat:2}}€</span>
            <span class="menu_list_ingredients">{{pizza.ingredients}}</span>
            {% if pizza.vegetarienne %}
                <span class="menu_list_badge">VÉGÉTARIENNE</span>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</body>
</html>